slug = "multiple_inheritance_cars"
authors = ["Jane Doe <jane@uzh.ch>"]
license = "CC BY 4.0"
max_attempts = 5
refill = 86400
max_points = 4.5

[information.en]
title = "Types of cars"
instructions_file = "instructions_en.md"

[evaluator]
docker_image = "python:latest"
run_command = "python -m task.script"
test_command = "python -m unittest discover -v task"
grade_command = "python -m unittest grading.tests"

[files]
visible = [
  "task/car.py",
  "task/combustion_car.py",
  "task/electric_car.py",
  "task/hybrid_car.py",
  "task/script.py",
  "task/test_cars.py",
  "task/resource/cars.png",
]
editable = [
  "task/car.py",
  "task/combustion_car.py",
  "task/electric_car.py",
  "task/hybrid_car.py",
  "task/script.py",
  "task/test_cars.py",
]
grading = [
  "grading/basic.py",
  "grading/info_hiding.py",
  "grading/inheritance.py",
  "grading/combustion_car.py",
  "grading/electric_car.py",
  "grading/hybrid_car.py",
]
solution = [
  "solution/car.py",
  "solution/combustion_car.py",
  "solution/electric_car.py",
  "solution/hybrid_car.py",
]

