slug = "multiple_inheritance_cars"
authors = ["Jane Doe <jane@uzh.ch>"]
license = "CC BY 4.0"
max_attempts = 5
refill = 86400
max_points = 4.5

[information.en]
title = "Types of cars"
instructions_file = "instructions_en.md"

[evaluator]
docker_image = "python:latest"
run_command = "python script.py"
test_command = "python -m unittest discover -v public"
grade_command = "python -m unittest discover grading"

[files]
visible = [
  "public/car.py",
  "public/combustion_car.py",
  "public/electric_car.py",
  "public/hybrid_car.py",
  "public/script.py",
  "public/test_cars.py",
  "public/resource/cars.png",
]
editable = [
  "public/car.py",
  "public/combustion_car.py",
  "public/electric_car.py",
  "public/hybrid_car.py",
  "public/script.py",
  "public/test_cars.py",
]
grading = [
  "grading/tests_0_smoke_tests.py",
  "grading/tests_1_info_hiding_tests.py",
  "grading/tests_1_inheritance.py",
  "grading/tests_2a_combustion_car.py",
  "grading/tests_2b_electric_car.py",
  "grading/tests_2c_hybrid_car.py",
]
solution = [
  "solution/car.py",
  "solution/combustion_car.py",
  "solution/electric_car.py",
  "solution/hybrid_car.py",
]

